# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on:
  repository_dispatch:
    types: [some-word]
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
